server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
      
zuul:
  ignoredServices: '*'
  routes:
    web-service:
      path: /**
      serviceId: web-service
      url: http://localhost:9090/
    post-service:
      path: /posts/**
      serviceId: post-service
      url: http://localhost:9091/
    user-service:
      path: /users/**
      serviceId: user-service
      url: http://localhost:9092/